### ISSUE TITLE
Récuperer la liste des aides

### ISSUE THREAD

**Issue by lutangar** [betagouv/VApp#55]
- v0 CSV
- V1 DB
- V2 DB mis à jour regulierement

**Comment by lutangar** [comment]
@louispinot pour le moment v0.5, ameliorer le process pour v1/v2 automatiser.

**Comment by louispinot** [comment]
@lutangar j'ai créé un ticket complémentaire #61, à groomer car je sais pas ce que tu voulais dire par V0,5 ;)
