### ISSUE TITLE
🔥 La recherche ne porte que sur les aides contenant 200 à 2000 tokens

### ISSUE THREAD

**Issue by louispinot** [betagouv/VApp#62]
Proposition de limiter le scope de recherche aux aides contenant 200 à 2000 token temporairement, pour accélérer les délais de réponses sur la V1, en attendant de pouvoir mieux filtrer cf #32 t d'augmenter les perf de l'IA

**Comment by Acrend** [comment]
@lutangar oui c'est possible nous pouvons utiliser :
- Un algorithme de sélection aléatoire régressif. Une solution « simple » consiste à sélectionner aléatoirement un premier ensemble de Nj (par exemple, 50) aides. Lors du premier scoring, on élimine les Ni (par exemple, 20) aides les moins pertinentes, puis on réintègre aléatoirement Ni nouvelles aides dans la sélection. Il est possible de déterminer statistiquement le meilleur ratio entre Nj et Ni, mais cela peut être fastidieux.

- Implémenter un RAG (Retrieval-Augmented Generation) peut ne pas être tout à fait adapté et nécessite de repenser l'architecture complète de l'application, en intégrant un véritable backend IA.

**Comment by lutangar** [comment]
Avec les aides entre 500-1500:
```
Nombres d'aides applicables par audience:
- Intercommunalité / Pays: 808
- Association: 581
- Commune: 856
- Recherche: 120
- Agriculteur: 129
- Collectivité d’outre-mer à statut particulier: 176
- Etablissement public dont services de l'Etat: 464
- Département: 480
- Entreprise publique locale (Sem, Spl, SemOp): 333
- Entreprise privée: 604
- Région: 296
- Particulier: 198
```

Ces params sont en evn :
```
AIDE_DESCRIPTION_MIN_TOKEN=500
AIDE_DESCRIPTION_MAX_TOKEN=1500
```

Donc modifiable depuis l'interface Scalingo.
