### ISSUE TITLE
Load balancing

### ISSUE THREAD

**Issue by lutangar** [betagouv/VApp#65]
Une solution qui est, en théorie, rapide à mettre en œuvre, pour un gain de perf conséquent et moins coûteux qu'un instance GPU supérieur.

Faire tourner plusieurs (2 pour commencer) backend Ollama sur instance GPU L4 et de répartir les requêtes Http en Round Robin.

__Scaleway__ propose des Load Balancer mais nous n'avons pas réussi à le mettre en œuvre.
Un simple`curl` sans paramètres sur l'ip du frontend du load balancer renvoi la page par défaut de nginx `<title>Welcome to nginx!</title>`.
Alors que nous nous attendons à ce que cette requête soit transmise au backend qui devrait renvoyer un `Unauthorized` sans les credentials adéquates.

**Comment by Acrend** [comment]
Le problème était qu'Ollama, par défaut, n'autorisait que les requêtes directes en local et ne supportait pas les redirections. Solution : ajouter OLLAMA_HOST=0.0.0.0 comme variable d'environnement.
